server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/capgeminitest?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: mapperxml/*.xml